name: EAS Update Deployment

on:
  push:
    branches:
      - main  # GitHub branch to trigger this workflow

jobs:
  eas_update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with EAS
        run: echo ${{ secrets.EAS_ACCESS_TOKEN }} | eas login

      - name: Get latest commit message
        id: commit_message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Run EAS Update
        run: eas update --branch preview --message "${{ env.message }}"